baseURL = "https://xfce.org/"
languageCode = "en-us"
title = "Xfce Desktop Environment"
theme = "xfce"
custom_css = [ "css/reset.css" ]

[menus]
   [[menus.inter]]
      name = "Home"
      pageRef = "/"
      weight = 10
   [[menus.inter]]
      name = "Docs"
      url = "https://docs.xfce.org/"
      weight = 20
   [[menus.inter]]
      name = "Archive"
      url = "http://archive.xfce.org/"
      weight = 30
   [[menus.inter]]
      name = "Wiki"
      url = "https://wiki.xfce.org/"
      weight = 40
   [[menus.inter]]
      name = "Forum"
      url = "https://forum.xfce.org/"
      weight = 50
   [[menus.inter]]
      name = "Bugs"
      url = "https://gitlab.xfce.org/"
      weight = 60
   [[menus.inter]]
      name = "Blog"
      url = "https://blog.xfce.org/"
      weight = 70
   [[menus.inter]]
      name = "Translate"
      url = "https://docs.xfce.org/contribute/translate/start"
      weight = 80
   [[menus.inter]]
      name = "Git"
      url = "https://gitlab.xfce.org/"
      weight = 90
   [[menus.main]]
      name = "Home"
      pageRef = "/"
      weight = 10
   [[menus.main]]
      name = "About"
      pageRef = "/about"
      weight = 20
   [[menus.main]]
      name = "Download"
      pageRef = "/download"
      weight = 30
   [[menus.main]]
      name = "Community"
      pageRef = "/community"
      weight = 40
   [[menus.main]]
      name = "Get Involved"
      pageRef = "/getinvolved"
      weight = 50
   [[menus.main]]
      name = "Projects"
      pageRef = "/projects"
      weight = 60
